// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1PWbwmAqjbfjJrLooqsvuyH_bKSffLI',
    appId: '1:742838170163:android:f43281ae676aed29ce2946',
    messagingSenderId: '742838170163',
    projectId: 'fixnow-8f2bb',
    storageBucket: 'fixnow-8f2bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugz11_uj94FLXzzqcHrWTIWKI4sq6Qw4',
    appId: '1:742838170163:ios:962c8d1fdc1244a3ce2946',
    messagingSenderId: '742838170163',
    projectId: 'fixnow-8f2bb',
    storageBucket: 'fixnow-8f2bb.firebasestorage.app',
    androidClientId: '742838170163-p37t19svf7o4dv0qo8p4jkcir2dqof15.apps.googleusercontent.com',
    iosClientId: '742838170163-19rbgn4a59gsvf82ngk4cm6sdj2ls68u.apps.googleusercontent.com',
    iosBundleId: 'com.shaplogicians.thekaonline',
  );

}